### PR TITLE
Update Travis configuration with PHP 7.1 and nightly

### PR DESCRIPTION
**Pull request by jdecool**

### CODE REVIEW

**Comment by skwi** [comment]
Seems like atoum is not working with PHP 7.1 😞

**Comment by jdecool** [comment]
Not yet.

See https://github.com/atoum/atoum/pull/615 for more informations.

**Comment by skwi** [comment]
Since the PR doesn't break the library code itself, I suggest we merge it.

**Comment by jdecool** [comment]
But the build will appear broken on the project homepage.

We can add PHP 7.1 in `allow_faillures`, but I think it lose interest to add this testing version.

I'm in favor to wait the Atoum PHP 7.1 compatibility before to merge this PR.

**Comment by skwi** [comment]
agreed

**Comment by jdecool** [comment]
Tests fixed by using the latest atoum pre-version for PHP 7.1

**Comment by skwi** [comment]
+1

**Review by skwi — APPROVED** [review]

**Pull request merged**
